name: Build & Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install Wasm Pack
      run: rustup default nightly && curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - uses: pnpm/action-setup@v4
      with:
        version: 8
    - name: Build Demo
      run: cd frontend && pnpm install && pnpm run build
    - name: Deploy using Terraform
      env: 
        TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        TF_VAR_CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      run: terraform apply -auto-approve
      
